meta_product_name: "Road Trips"
meta_title: "Road Trips - Product tagline"
meta_description: "The Road Trips is an application for finding or creating the trip after our studies. The most economical way to circumnavigate the globe is to voyage with Road Trip."
meta_image: "cover.png" # should exist in `app/assets/images/
